In [2]:
import torch.nn as nn
import torch

In [17]:
embedding_layer = nn.Embedding(num_embeddings=19,embedding_dim=4, _weight=torch.rand([19, 4]))



In [21]:
embedding_layer(torch.Tensor([2]).int())

tensor([[0.4997, 0.2316, 0.0300, 0.4346]], grad_fn=<EmbeddingBackward0>)

In [2]:
import os
path_join = lambda *path: os.path.abspath(os.path.join(*path))
root_dir = "./"  # Replace with your actual root directory
embedder_name = "your_embedder_name"  # Replace with your actual embedder name
local_path = path_join(root_dir, embedder_name, "..")
print(local_path)

/home/sxr280/BERTLocRNA


In [5]:
import torch
torch.tensor([[1,2,3], [2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [10]:
a = {"a": [1,2,3], "b": [4,5,6]}
torch.tensor(list(a.values()))

tensor([[1, 2, 3],
        [4, 5, 6]])